### PR TITLE
Ittn 045 update wifi

### PR DESCRIPTION
**Pull request by dtapiacl**
Cristian, i would appreciate your review before merging to Master.

### CODE REVIEW

**Comment by csilva-cl** [comment]
I would remove the usernames in the photos and either replace them by <username> or blur them out. 

Also please blur out the ssid that are not important.

**Review by csilva-cl — CHANGES_REQUESTED** [review]
Please blur out usernames and ssid not important for the document.

**Comment by dtapiacl** [comment]
Hi @csilva-cl , suggested changes were made to the branch. I would appreciate your review once more.

**Review by csilva-cl — APPROVED** [review]
All great, thanks.

**Pull request merged**
